### ISSUE TITLE
Parameter not occurring in the rate equation

### ISSUE THREAD

**Issue by milddaa** [SystemsBioinformatics/stochpy#4]
Hello,

I have a problem with the stochpy reading the model file (in psc format). It gives an error:

"Warning: species "x" has not been initialised
Info: "D1" has been initialised but does not occur in a rate equation
Info: "D2" has been initialised but does not occur in a rate equation
Info: "k01" has been initialised but does not occur in a rate equation
Info: "k02" has been initialised but does not occur in a rate equation
Info: "k1" has been initialised but does not occur in a rate equation
Info: "k2" has been initialised but does not occur in a rate equation
Info: "kt1" has been initialised but does not occur in a rate equation
Info: "kt2" has been initialised but does not occur in a rate equation"

However, the model psc file seems to be in correct format:

#Reactions

R1: 
    x > $pool
    -1*k0*x

R2: 
    x + x > y 
    -1*k12*x*x + 2*k21*y

R3: 
    D0 + P > D0 + P + n*x
    n*kt1*D0*P

R4: 
    D0 + y > D1
    -1*k1*y*D0 + k01*D1

R5: 
    D1 + P > D1 + P + n*x
    n*kt2*D1*P

R6: 
    D1 + y > D2
    -1*k2*y*D1 + k02*D2*P

x = 0.5
y = 0
D0 = 0
D1 = 0
D2 = 0
P = 0.5

k0 = 1
k01 = 1
k02 = 1
k1 = 10
k2 = 10
k12 = 15
k21 = 1
kt1 = 10
kt2 = 10

Do you have an idea of why this package would be giving me an error?

Thank you!

**Comment by bgoli** [comment]
Hi thanks for your detailed question.

Looking at the above code the problem is in the definition of your rate equations. The PSC format is very similar to Python or MATLAB so you need to explicitly write any multiplications (please see this [document](http://pysces.sourceforge.net/docs/inputfile_doc.html#basic-model-definition for more information). For example:

```-1k0x``` should probably be ```-1*k0*x``` and
```-1k12xx + 2k21*y```  as ```-1*k12*x*x + 2*k21*y```

Also, is the ```nx``` in the stoichiometry ```D1 + P > D1 + P + nx``` correct?

Hope this helps.

**Comment by milddaa** [comment]
Thank you for your quick response! The lack of multiplications was just a consequence of copy-pasting, sorry. The removal of "Ns" helped at first, but it seems that the bigger problem that I was facing is that StochPy does not support reversible reactions.

**Comment by tmd200** [comment]
I think reversible reactions should be split into two irreversible.

Op do 27 jun. 2019 11:27 schreef milddaa <notifications@github.com>:
